Automate encryption using GCP KMS API
teradici/cloud_deployment_scripts pull request #12
Opened 2020-01-30 22:48 UTC by Edwin-Pau

When using KMS encryption for the secrets inside the deployments'
tfvars files, users can now run a python script which will automate
the creation of the key ring, crypto key, and the encryption of the
tfvars secrets using the newly created crypto key.

Signed-off-by: Edwin Pau <epau@teradici.com>

2020-01-31 17:23 UTC, shermanyin commented on tools/gcp_kms_encrypt_secrets.py
> +    main()
newline at end of file please.

2020-01-31 17:23 UTC, shermanyin commented on tools/gcp_kms_encrypt_secrets.py
> +from google.cloud import kms_v1
alphabetical order imports

2020-01-31 17:24 UTC, shermanyin commented on tools/gcp_kms_encrypt_secrets.py
> +# Driver of this script
this comment is not needed

2020-01-31 17:30 UTC, shermanyin requested changes
hey I just took a one minute look at the code. I think it's a great idea to have this helper script. 
- could you please include instructions in the appropriate section of the readme file on how to use this? you should offer 2 options: 1) for the experienced, just tell them to include encrypted strings in the tfvars. 2) for the easy way, run this python script
- instead of asking users to edit this file, you should make user either enter the parameters like project-id, credentials-file, ring_id, etc in run time (e.g. interactively on the CLI) or in a config file.  
- or better yet, maybe we can ask users to enter the plain text secrets in the tvfars file, then run this script and this script will parse the tfvars for things it needs like project-id, then overwrite the file with encrypted secrets where needed.  so this way, the user enters info only in one place (tfvars), run this script ON that file which encrypts the secrets in place, then they have a tfvars that they can directly use for the deployment.

2020-01-31 18:08 UTC, Edwin-Pau commented
Noted! Will make the appropriate changes and create a new pull request when ready.

2020-02-06 18:29 UTC, Edwin-Pau commented
A new branch (gcp-kms-script) and pull requested is created to better reflect the functionality of the script since it now encrypts and decrypts. New pull request will reflect code changes made per the comments here.

2020-02-06 18:29 UTC, closed without merging