Use CAM service account instead of CAC token (multi-region)
teradici/cloud_deployment_scripts pull request #14
Opened 2020-02-03 23:33 UTC by Edwin-Pau

2020-02-06 02:07 UTC, shermanyin requested changes

2020-02-06 02:07 UTC, shermanyin commented on deployments/gcp/multi-region/terraform.tfvars.sample
> +# kms_cryptokey_id   = "projects/<project-id>/locations/<location>/keyRings/<keyring-name>/cryptoKeys/<key-name>"
why the extra spaces before "="?

2020-02-06 02:07 UTC, shermanyin commented on modules/gcp/cac-igm/main.tf
> +    "${path.module}/${local.cam_script_name}.tmpl",
ideally we have a generic script, and these values are passed to the startup scripts which calls cac-cam.py with these values as command line arguments.

2020-02-06 02:07 UTC, shermanyin commented on modules/gcp/cac-igm/main.tf
> +      ssl_key     = "",
why does the script need ssl_key/cert?

2020-02-06 02:07 UTC, shermanyin commented on modules/gcp/cac-igm/main.tf
> +  cam_credentials_name = "cam-cred.json"
i'd call this cam_credentials_json or cam_credentials_file

2020-02-06 02:07 UTC, shermanyin commented on modules/gcp/cac-igm/main.tf
> +  cam_script_name      = "cac-cam.py"
cam_script?

2020-02-06 02:07 UTC, shermanyin commented on modules/gcp/cac-igm/cac-startup.sh.tmpl
> +    log "Retrieving connector token..."
maybe for another commit but we should clean up the use of log vs echo in this file

2020-02-06 02:07 UTC, shermanyin commented on modules/gcp/cac-igm/cac-startup.sh.tmpl
> +    apt install -y python3
i think we should combine this and other stuff we need to install to one place where it install all requirements.  doing apt-get update a 2nd time is not needed.

2020-02-06 02:07 UTC, shermanyin commented on modules/gcp/cac-igm/cac-startup.sh.tmpl
> +        get_cac_token
if you're running the same function at the end of both "if" and "else", put it outside the if/else clause

2020-02-06 02:07 UTC, shermanyin commented on modules/gcp/cac-igm/cac-startup.sh.tmpl
> +    CAC_TOKEN=`python3 ${cam_script_name}`
your script already has "#!/usr/local/bin/python3" so I don't think you need to put python3 in front.

2020-02-06 02:07 UTC, shermanyin commented on modules/gcp/cac-igm/cac-cam.py.tmpl
> +CAM_CREDENTIALS_FILE = "cam-cred.json"
API_URL should have cam.teradici.com as default but also allow over-ride with command line options
CAM_CREDENTAILS_FILE should be a command line argument.

2020-02-06 02:07 UTC, shermanyin commented on modules/gcp/cac-igm/cac-cam.py.tmpl
> +iso_time = datetime.datetime.utcnow().isoformat(timespec='seconds').replace(':','').replace('-','') + 'Z'
With many connectors, I think there will need to be a way for users to see which connector corresponds to which VM in the cloud.  So I think the hostname should be in here somewhere.  Also, we might want to also specify the region and/or zone that this VM is in so we know how many connectors are in each zones.  Maybe something like "us-west2-vm-cac-2"  or something like that? You should be able to find a bunch of relevant info from the metadata server.

2020-02-06 02:07 UTC, shermanyin commented on modules/gcp/cac-igm/cac-cam.py.tmpl
> +    cac_deployment_id  = get_deployment_id(auth_token)
Why is this needed? can't you get deploymentId from the CAM credentials file?

2020-02-06 02:07 UTC, shermanyin commented on modules/gcp/cac-igm/cac-cam.py.tmpl
> +# Entry point to this script
no need for this comment

2020-02-06 02:07 UTC, shermanyin commented on modules/gcp/cac-igm/cac-cam.py.tmpl
> +        sys.stdout.write(main())
can you just use print()?

2020-02-06 02:07 UTC, shermanyin commented on modules/gcp/cac-igm/cac-cam.py.tmpl
> +        sys.exit(1)
newline at end of file

2020-02-06 02:07 UTC, shermanyin commented on modules/gcp/cac-igm/cac-startup.sh.tmpl
> +    CAC_TOKEN=`python3 ${cam_script_name}`
You should also check "$?" to see the previous command failed.

2020-02-06 02:10 UTC, shermanyin commented on modules/gcp/cac-igm/cac-cam.py.tmpl
> +# Copyright (c) 2020 Teradici Corporation
Thils file should not need to be a template

2020-02-06 02:13 UTC, shermanyin commented on modules/gcp/cac-igm/main.tf
> +    "${path.module}/${local.cam_script_name}.tmpl",
I don't see where the variables are used in the tmpl

2020-02-06 21:03 UTC, Edwin-Pau commented on deployments/gcp/multi-region/terraform.tfvars.sample
> +# kms_cryptokey_id   = "projects/<project-id>/locations/<location>/keyRings/<keyring-name>/cryptoKeys/<key-name>"
Will discard this change - I believe I accidentally added this file in this branch. I've updated all sample files in the other branch (gcp-kms-script).

2020-02-06 23:03 UTC, Edwin-Pau commented on modules/gcp/cac-igm/cac-cam.py.tmpl
> +    cac_deployment_id  = get_deployment_id(auth_token)
Looks like we don't need it - changed to read directly from CAM JSON.

2020-02-11 23:54 UTC, Edwin-Pau commented
All comments addressed, will be creating new pull request with all the changes.

2020-02-11 23:54 UTC, closed without merging