Change active directory variable names for AWS
teradici/cloud_deployment_scripts pull request #28
Opened 2020-02-15 01:43 UTC by Edwin-Pau

For the AWS single connector deployment, all service_account variables
have been renamed to ad_service_account to avoid confusion with other
types of service accounts.

Signed-off-by: Edwin Pau <epau@teradici.com>

2020-02-18 21:21 UTC, shermanyin requested changes

2020-02-18 21:21 UTC, shermanyin commented on modules/aws/cac/cac-startup.sh.tmpl
> +        SERVICE_ACCOUNT_PASSWORD=$(aws kms decrypt --region ${aws_region} --ciphertext-blob fileb://<(echo "${ad_service_account_password}" | base64 -d) --output text --query Plaintext | base64 -d)
might as well change this too for consistency?

2020-02-18 21:21 UTC, shermanyin commented on modules/aws/centos-gfx/centos-gfx-startup.sh.tmpl
> +        SERVICE_ACCOUNT_PASSWORD=${ad_service_account_password}
same here

2020-02-18 21:21 UTC, shermanyin commented on modules/aws/centos-std/centos-std-startup.sh.tmpl
> +        SERVICE_ACCOUNT_PASSWORD=${ad_service_account_password}
here as well and same for other files

2020-02-18 23:08 UTC, Edwin-Pau commented
- Updated global variable names as requested and force pushed to update pull request.
- First time using rebase squash (had some issues with git when I rebased off staging).
- Changes tested and deployed successfully on AWS.

2020-02-19 01:00 UTC, shermanyin approved these changes

2020-02-19 01:02 UTC, merged