Use variables for PCoIP Agent download location
teradici/cloud_deployment_scripts pull request #34
Opened 2020-02-20 19:34 UTC by Edwin-Pau

As part of the startup scripts for CentOS machines, the download
location for PCoIP agent has been changed to use variables instead
for better flexibility and to keep the consistency with the Windows
startup scripts.

Signed-off-by: Edwin Pau <epau@teradici.com>

2020-02-20 22:35 UTC, Edwin-Pau commented
In CentOS, it downloads the rpm into /var/cache/yum as the default path before installing, I'm not sure if you wanted this changed instead of just the .repo file.

2020-02-24 22:38 UTC, shermanyin requested changes
Thanks for correcting the logs from these scripts.

Sorry the problem description wasn't very clear.  What I meant was in windows there is the "pcoip_agent_location" variable to indicate which URL to fetch the driver, where as it is hard-coded in CentOS.  So What i was thinking was just makeing "https://downloads.teradici.com/rhel/" a variable that could be changed by terraform user.

2020-03-04 23:58 UTC, shermanyin requested changes
Step in the right direction, however I would like to still see some changes.

And since you will be creating a new patchset anyway, could you move all the comments / logs / typo changes to one separate commit (no functional difference), and the parameterization of the repo/key a separate commit?

2020-03-04 23:58 UTC, shermanyin commented on modules/aws/centos-gfx/centos-gfx-startup.sh.tmpl
> +        teradici_pubkey=teradici.pub.gpg
this variable doesn't seem to accomplish anything since it's not used anywhere else.

2020-03-04 23:58 UTC, shermanyin commented on modules/aws/centos-gfx/vars.tf
> +  default     = "https://downloads.teradici.com/rhel/"
Given how the agent is installed by downloading a repo and its public key, i think for CentOS it make sense to have a pcoip_agent_repo_public_key and default to https://downloads.teradici.com/rhel/teradici.pub.gpg and a pcoip_agent_repo_url and default to https://downloads.teradici.com/rhel/pcoip.repo

2020-03-04 23:58 UTC, shermanyin commented on modules/aws/centos-gfx/centos-gfx-startup.sh.tmpl
> +        wget --retry-connrefused --tries=3 --waitretry=5 -O /etc/yum.repos.d/pcoip.repo $PCOIP_AGENT_LOCATION$PCOIP_AGENT_REPO
can we just specify the output directory to be in /etc/yum.repos.d/ and then the file should be unchanged from where it is downloaded from? that way we don't have to hard code "pcoip.repo".

2020-03-04 23:58 UTC, shermanyin commented on modules/aws/win-gfx/win-gfx-startup.ps1.tmpl
> +        "Using custom PCoIP Agent filename..."
custom sounds funny. maybe user-specified?

2020-03-06 03:39 UTC, Edwin-Pau commented
- Resolved all the comments above
- Removed all logging style, grammar, spelling changes
- Tested all 8 workstation types with the client (GCP + AWS)

2020-03-10 18:38 UTC, shermanyin approved these changes

2020-03-10 18:38 UTC, merged