AWS: Cleanup provisioning scripts
teradici/cloud_deployment_scripts pull request #94
Opened 2020-05-01 22:20 UTC by Edwin-Pau

Applied the same changes from the GCP provisioning script cleanup branch. These changes in the provisioning scripts include cleaning up of the logging messages, refactoring of various functions, and renaming the startup scripts to provisioning scripts.

Signed-off-by: Edwin-Pau <epau@teradici.com>

2020-05-22 23:08 UTC, shermanyin requested changes

2020-05-22 23:08 UTC, shermanyin commented on deployments/aws/lb-connectors/terraform.tfvars.sample
> +# in the storage bucket holding the provisioning scripts, as well as in the provisioning
`> 80 chars

2020-05-22 23:08 UTC, shermanyin commented on deployments/aws/single-connector/terraform.tfvars.sample
> +# in the storage bucket holding the provisioning scripts, as well as in the provisioning
`> 80 chars

2020-05-22 23:08 UTC, shermanyin commented on modules/aws/centos-gfx/centos-gfx-provisioning.sh.tmpl
> +    if [[ -z "$PCOIP_REGISTRATION_CODE" ]]; then
heads up that pcoip reg code is no longer required due to LLS support, so this will conflict with my LLS changes.
this applies to all workstations.

2020-05-22 23:08 UTC, shermanyin commented on modules/aws/dc/main.tf
> +  provisioning_file                 = "C:/Temp/provisioning.ps1"
spacing

2020-05-27 00:25 UTC, Edwin-Pau commented on modules/aws/centos-gfx/centos-gfx-provisioning.sh.tmpl
> +    if [[ -z "$PCOIP_REGISTRATION_CODE" ]]; then
I will wait for LLS to merge first, then manually merge this branch with LLS changes.

2020-05-29 01:13 UTC, shermanyin approved these changes

2020-06-02 02:50 UTC, merged